server:
  port: 8080

spring:
  application:
    name: admin-server
  boot:
    admin:
      discovery:
        enabled: true
      context-path: /admin

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
