server:
  port: 9090

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/products/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
