server:
  port: 9090

spring:
  application:
    name: auth-service
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
  datasource:
    url: jdbc:postgresql://172.19.0.2:5432/userdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 722384219307-do2khkmv9qc4p0f5bkf0lgmamj4rutop.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret: your-secret-key
  expiration: 3600000 # 1 saat

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
